iersion: 0.0
os: linux

files:
        - source: /
          destination: /var/www/html/humhub

permissions:
        - object: /var/www/html/humhub
          owner: www-data
          group: www-data
hooks:
        ApplicationStop:
              - location: script/Appstop.sh

        BeforeInstall:
              - location: script/beforeinstall.sh

        Install:         
              - location: script/script.sh

        AfterInstall:
              - location: script/apache.sh

